### ISSUE TITLE
Run ud_to_um.sh. 

### ISSUE THREAD

**Issue by fym0503** [technion-cs-nlp/Individual-Neurons-Pitfalls#1]
Hi,

Thanks for your code. I am wondering where is the ud_to_um.sh file? I cannot find it.
Thanks

**Comment by omerant** [comment]
Hi!
Thank you for this issue.
The file somehow went missing. I just added it, please see if it works for you.

**Comment by fym0503** [comment]
It seems that LinearCorrelationAnalysis is also missing. It is present in Gaussian.py
from linearCorrelationAnalysis import LCA

**Comment by omerant** [comment]
Hi, this import was redundant. I removed it. Please try now.
Thank you
