### ISSUE TITLE
UD to UM data

### ISSUE THREAD

**Issue by fym0503** [technion-cs-nlp/Individual-Neurons-Pitfalls#2]
Hi, I am running your code and I have trouble configuring the data. After running ud to um conversion, I cannot find the label_to_idx.pkl. Could you please share a small piece of your processed data so that I can check what's wrong about my code?

**Comment by omerant** [comment]
Hi,
Did you run `LinearWholeVector.py` (step 1 in probing experiments)? `label_to_idx.pkl` should be created after that.
Note that you should also run `parsing.py` (step 6 in setup) before.
